[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build --workspace=apps/web-mvp"

[deploy]
startCommand = "npm run start --workspace=apps/web-mvp"
healthcheckPath = "/"
healthcheckTimeout = 100
